

service: hello-lambda # NOTE: update this with your service name


provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  profile: sbjs-demo



functions:
  hello:
    handler: handler.hello

resources:
  # Cognito
  - ${file(cognito-user-pool.yml)}

plugins:
   - serverless-appsync-plugin  

custom:
  appSync:
    name:  sbjs-demo-api
    authenticationType: AMAZON_COGNITO_USER_POOLS
    userPoolConfig:
      defaultAction: ALLOW # required # ALLOW or DENY
      userPoolId: us-west-2_nwDYnGR9h
    logConfig:
      loggingRoleArn: { Fn::GetAtt: [AppSyncLoggingServiceRole, Arn] } # Where AppSyncLoggingServiceRole is a role with CloudWatch Logs write access
      level: ALL # Logging Level: NONE | ERROR | ALL
    mappingTemplates:
      - dataSource: get_greeting_resolver_ds
        type: Query
        field: getGreeting
        request: "get-greeting-request-mapping-template.vtl"
        response: "get-greeting-response-mapping-template.vtl"
    dataSources:
      - type: AWS_LAMBDA
        name: get_greeting_resolver_ds
        description: 'Lambda DataSource'
        config:
          functionName: hello 


# note: hoping that there's default permission stuff so I won't have to think about it...